### ISSUE TITLE
Incomplete README on how to get started using this lib

### ISSUE THREAD

**Issue by dialex** [chef/inspec-azure#45]
I have set up my inspec profile as you recommended:

```yml
name: acceptance-tests
...
depends:
  - name: azure
    url: https://github.com/chef/inspec-azure/archive/master.tar.gz
```

However when I execute the tests `inspec exec .` I get the error below:

```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ms_rest_azure (LoadError)
  from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /var/lib/gems/2.3.0/gems/inspec-1.33.1/lib/inspec/dsl_shared.rb:14:in `require'
  from libraries/azure_backend.rb:1:in `load_with_context'
  ...
  from /usr/local/bin/inspec:23:in `load'
  from /usr/local/bin/inspec:23:in `<main>'
```

That's because Inspec can't find the required file `ms_rest_azure` on your `azure_backend.rb`. Indeed, **I searched your git repo and there's no file with that name**.

It seems you include some dependencies on your `Gemfile`, but what am I supposed to do? On your [readme](https://github.com/chef/inspec-azure#use-the-resources) you only mention adding the `depends`/`url` to the inspec profile... what am I missing?
